receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug

  jaeger:
    endpoint: app-jaeger:4317
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger ]
      #metrics:
      #receivers: [otlp]
      #processors: [batch]
      #exporters: [logging, jaeger]