receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  #logging:
  otlp/data-prepper:
    endpoint: app-prepper:21890
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp/data-prepper ]
    metrics:
      receivers: [ otlp ]
      exporters: [ otlp/data-prepper ]

