receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging: { }
  otlp:
    endpoint: 'app-data-prepper:21890'
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
      #metrics:
      #receivers: [ otlp ]
      #exporters: [ otlp ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp ]