receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/data-prepper:
    endpoint: app-data-prepper:4900
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/data-prepper ]
