receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
      #metrics:
      #receivers: [ otlp ]
      #exporters: [ otlp ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp ]